spring.application.name=Product_shop
server.port=9090
server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3306/pdsm26
spring.datasource.username=root
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
