spring.application.name=PrintPulse
server.port=9090
server.address=0.0.0.0

# MongoDB Atlas connection string. The URI must include /print_db.
# Example:
# mongodb+srv://<USERNAME>:<ENCODED_PASSWORD>@ase-naki-mongo.vcdwgus.mongodb.net/print_db?appName=Ase-Naki-Mongo
spring.mongodb.uri=mongodb+srv://azizul:MLwqPZwcU7WqNUbL@ase-naki-mongo.vcdwgus.mongodb.net/print_db?appName=Ase-Naki-Mongo

spring.thymeleaf.cache=false
